# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53eb5c7c54642c2a84ef0bcae11bed8f90e7e04098ac61984eecd3469045141689da752699f4ac33a023deaa5273286f9fe8ece8be0ed75ddc5ff65381c63d30

test:
  secret_key_base: 03e4529a0ae219dc3b78937edd3c3dbf1bd63283477631b05fc1b6f40abb2be61764e49b7e2b8d6d823da4751679bbdf66f9f88be6bbfcb5b4ec499da00938e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
